### ISSUE TITLE
Проверка бустинг

### ISSUE THREAD

**Issue by KochetovNicolai** [EtsuNDmA/DMIA-2016---Python#2]
1. Вопрос 2. Память здесь не самая большая проблема :) Глубокие деревья хорошо переобучаются. Например, 1-е дерево может запомнить всю выборку, а остальные обучаться на нулевой градиент.
2. Вопрос 3. Целевая переменная - это скорее (анти)градиент функции потерь. Он будет равен сдвигу для квадратичной функции потерь, но отличается, например, для логистической.
3. По поводу кода:
 +1 за expit
 ```
                regr = DecisionTreeRegressor(max_depth=self.max_depth)
                regr.predict = lambda X: np.zeros_like(X.shape[0], dtype=float)
 ``` 
Интересное решение, но фактически получается на 1 дерево меньше
 ``` 
                regr = DecisionTreeRegressor(max_depth=self.max_depth).fit(X, -grad)
            estimator = deepcopy(regr)
 ``` 
Здесь глубокую копию можно и не делать, и так создается новый объект
` y_pred = np.sign(y_pred-0.5)`
Казалось бы, классы - это 1 и -1. Зачем вычитать 0.5?
4. Плохая идея мерить качество по той выборке, на которой ты обучился. Сделай кроссвалидацию и посмотри на на качество. 
`cross_val_score(clf, X, y)`
На 100 деревьях должны получаться числа порядка 0.85

Засчитываю по модулю того, что будет сделана кросс-валидация

**Comment by EtsuNDmA** [comment]
> Засчитываю по модулю того, что будет сделана кросс-валидация
Т.е. будет засчитано только после выполнения кроссвалидации?
У меня везде написано clf.score(X, y), а нужно cross_val_score(clf, X, y) так? А ведь cross_val_score(clf, X, y) возвращает array, его нужно усреднить?

**Comment by KochetovNicolai** [comment]
Я поверил, что ты сможешь сделать кросс-валидацию, и уже засчитал :) 

> У меня везде написано clf.score(X, y), а нужно cross_val_score(clf, X, y) так?
Да, все верно.

> А ведь cross_val_score(clf, X, y) возвращает array, его нужно усреднить как в документации?
Да, можно усреднить. Вообще, зависит от того, что нужно в задаче. Минимум, например, тоже логично брать.
